#ifndef ESTADOS_H
#define ESTADOS_H

const int square1[14][14] =
{
    {BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB},
    {BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {BB,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int square2[14][14] =
{
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int mine[14][14] =
{
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,NN,GS,NN,NN,NN,NN,GS,NN,GS,GS,GF},
    {GF,GS,GS,GS,NN,NN,NN,NN,NN,NN,GS,GS,GS,GF},
    {GF,GS,GS,NN,NN,BB,BB,NN,NN,NN,NN,GS,GS,GF},
    {GF,GS,GS,NN,NN,BB,NN,NN,NN,NN,NN,GS,GS,GF},
    {GF,GS,GS,NN,NN,NN,NN,NN,NN,NN,NN,GS,GS,GF},
    {GF,GS,GS,NN,NN,NN,NN,NN,NN,NN,NN,GS,GS,GF},
    {GF,GS,GS,GS,NN,NN,NN,NN,NN,NN,GS,GS,GS,GF},
    {GF,GS,GS,NN,GS,NN,NN,NN,NN,GS,NN,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int mine2[14][14] =
{
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {GF,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,GF},
    {GF,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,GF},
    {GF,RR,RR,NN,RR,NN,NN,NN,NN,RR,NN,RR,RR,GF},
    {GF,RR,RR,RR,NN,NN,NN,NN,NN,NN,RR,RR,RR,GF},
    {GF,RR,RR,NN,NN,BB,BB,NN,NN,NN,NN,RR,RR,GF},
    {GF,RR,RR,NN,NN,BB,NN,NN,NN,NN,NN,RR,RR,GF},
    {GF,RR,RR,NN,NN,NN,NN,NN,NN,NN,NN,RR,RR,GF},
    {GF,RR,RR,NN,NN,NN,NN,NN,NN,NN,NN,RR,RR,GF},
    {GF,RR,RR,RR,NN,NN,NN,NN,NN,NN,RR,RR,RR,GF},
    {GF,RR,RR,NN,RR,NN,NN,NN,NN,RR,NN,RR,RR,GF},
    {GF,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,GF},
    {GF,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,RR,GF},
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int one[14][14] =
{
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,AA,AA,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,AA,AA,AA,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,AA,AA,AA,AA,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,AA,AA,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,AA,AA,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,AA,AA,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,AA,AA,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,AA,AA,AA,AA,AA,AA,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int two[14][14] =
{
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,VV,VV,VV,VV,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,VV,VV,VV,VV,VV,VV,GS,GS,GS,GF},
    {GF,GS,GS,GS,VV,VV,GS,GS,VV,VV,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,VV,VV,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,VV,VV,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,VV,VV,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,VV,VV,VV,VV,VV,VV,GS,GS,GS,GF},
    {GF,GS,GS,GS,VV,VV,VV,VV,VV,VV,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int three[14][14] =
{
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,RR,RR,RR,RR,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,RR,RR,RR,RR,RR,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,RR,RR,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,RR,RR,RR,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,RR,RR,RR,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,RR,RR,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,RR,RR,RR,RR,RR,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,RR,RR,RR,RR,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int flag[14][14] =
{
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,RR,RR,NN,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,RR,RR,RR,RR,NN,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,RR,RR,RR,NN,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,RR,RR,NN,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,NN,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,NN,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,NN,NN,NN,NN,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,NN,NN,NN,NN,NN,NN,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int symbol[14][14] =
{
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,NN,NN,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,NN,NN,GS,GS,GS,GS,GS,GF},
    {GF,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF},
    {GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int close_button[20][20] =
{
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GS,GS},
    {GS,GS,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GS,GS},
    {GS,GS,GS,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GS,GS,GS},
    {GS,GS,GS,GS,GC,GC,GC,GS,GS,GS,GS,GS,GS,GC,GC,GC,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GC,GC,GC,GS,GS,GS,GS,GC,GC,GC,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GC,GC,GC,GS,GS,GC,GC,GC,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GC,GC,GC,GS,GS,GC,GC,GC,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GC,GC,GC,GS,GS,GS,GS,GC,GC,GC,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GC,GC,GC,GS,GS,GS,GS,GS,GS,GC,GC,GC,GS,GS,GS,GS},
    {GS,GS,GS,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GS,GS,GS},
    {GS,GS,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GS,GS},
    {GS,GS,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS}
};
const int restart_button[28][28] =
{
    {BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB},
    {BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,BB,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GC,GC,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GC,GC,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GC,GA,GA,GC,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GC,GA,GA,GC,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GC,GA,GA,GA,GC,GS,GS,GS,GS,GS,GS,GS,GS,GC,GA,GA,GA,GC,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GC,GA,RS,GA,GA,GC,GS,GS,GS,GS,GS,GS,GC,GA,GA,RS,GA,GC,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GC,GA,RS,RS,GA,GC,GS,GS,GS,GS,GS,GS,GC,GA,RS,RS,GA,GC,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GC,GA,RS,RS,GA,GA,GC,GC,GC,GC,GC,GC,GA,GA,RS,RS,GA,GC,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GC,GA,GA,GA,GA,GA,GA,GB,GB,GB,GB,GA,GA,GA,GA,GA,GA,GC,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GC,GA,GA,GA,GA,GA,GA,GA,GB,GB,GA,GA,GA,GA,GA,GA,GA,GC,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GC,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GC,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GC,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GC,GS,GS,GF,GF},
    {BB,BB,GS,GC,GA,GA,GA,GA,GA,GC,GC,GA,GA,GA,GA,GA,GA,GC,GC,GA,GA,GA,GA,GA,GC,GS,GF,GF},
    {BB,BB,GS,GS,GC,GA,GA,GA,GA,GC,GC,GA,GA,GA,GA,GA,GA,GC,GC,GA,GA,GA,GA,GC,GS,GS,GF,GF},
    {BB,BB,GS,GC,GA,GA,GA,GA,GA,GC,GC,GA,GA,GA,GA,GA,GA,GC,GC,GA,GA,GA,GA,GA,GC,GS,GF,GF},
    {BB,BB,GS,GS,GC,GC,GB,GB,GA,GA,GA,GA,RS,RS,RS,RS,GA,GA,GA,GA,GB,GB,GC,GC,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GC,GB,GA,GA,GA,GA,GA,RS,RS,GA,GA,GA,GA,GA,GB,GC,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GC,GC,GA,GA,GA,GA,GA,GA,GA,GA,GA,GA,GC,GC,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GC,GC,GC,GC,GC,GC,GC,GC,GC,GC,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GF,GF},
    {BB,BB,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF},
    {BB,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF,GF}
};

const int corona[24][24] =
{
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,NN,NN,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,NN,AD,AD,NN,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,NN,DS,AD,NN,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,NN,NN,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS,GS},
    {GS,NN,NN,GS,GS,GS,GS,GS,GS,GS,NN,DS,AD,NN,GS,GS,GS,GS,GS,GS,GS,NN,NN,GS},
    {NN,DS,AD,NN,GS,GS,GS,GS,GS,GS,NN,DS,AD,NN,GS,GS,GS,GS,GS,GS,NN,AD,AD,NN},
    {NN,DS,DS,NN,GS,GS,GS,GS,GS,NN,DS,AD,AD,AD,NN,GS,GS,GS,GS,GS,NN,AD,AD,NN},
    {GS,NN,NN,DS,NN,GS,GS,GS,GS,NN,DS,AD,AD,AD,NN,GS,GS,GS,GS,NN,AD,NN,NN,GS},
    {GS,GS,NN,DS,AD,NN,NN,GS,NN,DS,AD,AD,AD,AD,AD,NN,GS,NN,NN,AD,AD,NN,GS,GS},
    {GS,GS,GS,NN,DS,AD,AD,NN,NN,DS,AD,AD,AD,AD,AD,NN,NN,AD,AD,AD,NN,GS,GS,GS},
    {GS,GS,GS,NN,DS,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,NN,GS,GS,GS},
    {GS,GS,GS,GS,NN,DS,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,NN,GS,GS,GS,GS},
    {GS,GS,GS,GS,NN,DS,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,AD,NN,GS,GS,GS,GS},
    {GS,GS,GS,GS,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,NN,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,NN,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,NN,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,NN,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,NN,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,DS,NN,GS,GS,GS,GS,GS},
    {GS,GS,GS,GS,GS,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,NN,GS,GS,GS,GS,GS}
};

#endif // ESTADOS_H
